name: Build and deploy Node.js app to Azure Web App - frontend-uptimeX

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Prepare standalone deployment
        run: |
          rm -rf deploy
          mkdir -p deploy
          cp -r .next/standalone/. deploy/
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/static
          # Next.js requires BUILD_ID alongside static assets when running standalone
          cp .next/BUILD_ID deploy/.next/BUILD_ID
          if [ -d "public" ]; then cp -r public deploy/public; fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./deploy
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-uptimeX'
          slot-name: 'Production'
          package: ./deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0EF1A91AECEA48729CFEB66797043C64 }}